name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test

    steps:
      - name: 체크아웃 소스코드
        uses: actions/checkout@v2

      - name: Python 설정
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Poetry 설치
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          poetry --version

      - name: 의존성 설치
        run: |
          poetry install --no-interaction --no-root

      - name: Pytest 실행
        env:
          MONGO_URI: "mongodb://test:test@localhost:27017"
        run: |
          poetry run pytest backend/tests/test_main.py